language: php

addons:
    code_climate:
            repo_token: b31faff683ba4c5181b75c762884b384ced325ff50739c832908bde60a5b0929

php:
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=dev-master

install:
  - composer install

script: vendor/bin/grumphp run
