language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=dev-master

install:
  - composer install

script: vendor/bin/grumphp
