language: php

addons:
  code_climate:
    repo_token: b31faff683ba4c5181b75c762884b384ced325ff50739c832908bde60a5b0929

cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=dev-master

install:
  - composer install --prefer-dist

script: 
  - vendor/bin/grumphp run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage/clover/coverage.xml
