language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=dev-master

install:
  - composer install --prefer-source --no-interaction

script: vendor/bin/grumphp
